### ISSUE TITLE
Xfwm theme not changing

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [themix-project/oomox#276] opened 2019-11-21 18:41 UTC
### What I did
Exported my theme with Arc Theme Style to generate theme for xfwm

### What I expected
A theme similar to Arc but with my colors for the headerbar,

### What happened 
I got an XFWM theme exactly identical to Arc's

### Other information
The gtk & icons theme worked as expected.

**Comment by actionless** [comment] 2019-11-21 20:33
if the issue is reproducible when running https://github.com/arc-design/arc-theme/blob/55ebbd4d868727b769c8c5ab902a4a503d9434af/change_color.sh directly -- please report the issue here: https://github.com/arc-design/arc-theme/issues

**Comment by actionless** [comment] 2019-11-21 20:41
from first glance it could be what xfwm needs a similar workaround as cinnamon and gnome-shell themes but as i'm not using neither of them - i didn't tried

**Comment by actionless** [comment] 2020-01-14 17:22
closing as the issue belongs to arc-design/arc-theme

**Closed by actionless** 2020-01-14 17:22 UTC
