### ISSUE TITLE
Unable to generate materia theme with latest inkscape on Arch Linux

### ISSUE THREAD

**Issue by adi1090x** [themix-project/oomox#389] opened 2021-07-24 10:30 UTC
As mentioned in the Title, Can't generate Materia theme. Stuck at `rendering gtk2 assets...` and consumes all memory.
Probably the inkscape issue, 

- Using `themix-full` version from AUR
- Inkscape Version : Inkscape 1.1 (c4e8f9ed74, 2021-05-24)

Would you be able to have a look at this issue?

**Comment by actionless** [comment] 2021-07-24 16:56
duplicate of https://github.com/themix-project/oomox/issues/387

**Closed by actionless** 2021-07-24 16:56 UTC
