### ISSUE TITLE
Redesign main lists based on GNOME HIG

### ISSUE THREAD

**Issue by nana-4** [themix-project/oomox#190] opened 2018-12-23 22:15 UTC
Mockup:

![image](https://user-images.githubusercontent.com/9556384/46919705-07027d00-d01e-11e8-9866-ba4b78e2cf03.png)

based on: https://developer.gnome.org/hig/stable/lists.html.en

Some design examples from GNOME's mockup:

- https://gitlab.gnome.org/Teams/Design/settings-mockups/blob/master/applications/applications-wires.png
- https://gitlab.gnome.org/Teams/Design/app-mockups/blob/master/tweaks/tweaks-wires.png

**Comment by actionless** [comment] 2018-12-23 23:15
i think the bigger problem which should be addressed in the list of the options, is to make some easier navigation.

currently, especially if terminal theme set to Manual mode, that list have way too many items to scroll, so i was thinking mb about some Notebook tabs or smth like that

**Comment by actionless** [comment] 2018-12-26 07:37
also i can't understand which style classes should i use to achieve the same appearance as shown on your mockup or in HIG -- when i installed gnome-tweaks (3.30.2) it looks totally different:

![2018-12-26--1545809783_964x750_scrot](https://user-images.githubusercontent.com/1655669/50437269-5b14c200-08e9-11e9-9e3c-56244c3e1b93.png)

i only can see in HIG they mentioned as "embedded lists" but i can't see anything related in the apidoc: https://developer.gnome.org/gtk3/stable/GtkListBox.html

**Comment by nana-4** [comment] 2018-12-27 07:12
> i was thinking mb about some Notebook tabs or smth like that

I also had an idea to use tabs or something like that. I'll create a mockup for that.

> when i installed gnome-tweaks (3.30.2) it looks totally different

gnome-tweaks has not adapted that style yet. Please try `gnome-control-center` -- which should be the best example so far.

**Comment by actionless** [comment] 2018-12-27 08:58
seems it's not gonna work without actual gnome running :(

```
$ gnome-control-center
**
ERROR:../gnome-control-center/shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
fish: “gnome-control-center” terminated by signal SIGABRT (Abort)
```

**Comment by actionless** [comment] 2018-12-27 09:00
gtk inspector is using such layout but idk how to inspect it with itself

**Comment by actionless** [comment] 2018-12-28 22:07
mb you could just make a screenshot of CSS nodes tree of the appropriate layout (with screenshot of that app itself)?

**Comment by nana-4** [comment] 2018-12-28 23:03
Of course! Here you are:
![image](https://user-images.githubusercontent.com/9556384/50530374-22225a80-0b40-11e9-8443-739807002171.png)

Please let me know if you need more screenshots.

**Comment by actionless** [comment] 2018-12-28 23:13
thanks! i'll try to play with it tonight or tomorrow morning!

**Comment by actionless** [comment] 2018-12-28 23:16
and also please think about some quick-navigation for the list, like splitting into tabs, or scrolling the list based on stackswitcher buttons or so on

**Comment by actionless** [comment] 2018-12-31 15:42
unfortunately info from CSS Nodes tree is not enough for recreating this :(
mb you know starting from which version gnome-tweaks having that layout so i can just open that tag from their repo and observe the code?

**Comment by actionless** [comment] 2018-12-31 15:44
or mb after we'll get some solution for navigating/splitting this long list such design approach (with "white" blocks) won't be applicable anymore so mb better first to design that navigation/splitting into tabs/whatever?

**Comment by nana-4** [comment] 2019-01-08 08:02
> mb you know starting from which version gnome-tweaks having that layout so i can just open that tag from their repo and observe the code?

Unfortunately, the mockup is only available but in real application it has not been applied yet :(

> or mb after we'll get some solution for navigating/splitting this long list such design approach (with "white" blocks) won't be applicable anymore so mb better first to design that navigation/splitting into tabs/whatever?

I agree. I'd like to create some mockups, but I don't have much time to do it. Sorry, but I'll address it soon.

**Comment by actionless** [comment] 2019-01-08 14:39
no worries, i also time-limited and apart from GUI redesign i am also doing some other small improvements to the app

for example yesterday i've added inhibititing logout/poweroff if there is unsaved themix theme

**Comment by actionless** [comment] 2019-01-09 23:56
thanks!

regarding Numix Style, that's separation is based on the following logic: Archdroid, Gnome-Colors and Numix-Icons are 3 different plugins, so first dropdown is selecting plugin. Next Numix-Icons have it's own plugin option, called Numix-Style, which at the end passing different arg to numix icons generation script. So if you want to improve, the only thing which can be done here is renaming those items, but they can't be merged together.

**Comment by actionless** [comment] 2019-01-10 00:37
Also regarding StackSwitcher sections:
i think it will be better to have instead of Spotify "Other" theme section, and put there everything what is under terminal theme options (including spotify).

from technical side of view, i mean the content of plugin's theme_model_other theme options list

**Comment by actionless** [comment] 2019-01-10 00:41
And also about design for import options (with cog wheel icon):
i think it should be the leftmost in stackswitcher, not rightmost
just from the logic what import is on the left of the topbar and also what usually those import options are meant to be accessed first before editing theme options -- because changing import options would overwrite theme options (but it will show a prompt dialog about that before)

**Comment by actionless** [comment] 2019-01-10 12:20
>  "Folder Icons Style" 

:+1: 


     
> I think it would be better to separate the "Terminal" and "Spotify" sections 

yup, i was thinking of "Theme, Icons, Terminal, Other", especially keeping in mind what in Flatpak installation Spotify plugin is not available at all


> . In my new idea, pressing the "Export" button while in "Terminal" section will export the terminal palette, and so on.

the number of export plugins is not limited, so it could became a bit misleading what one plugins are exporting their result implicitly on Export button and other would require explicitly selecting them in the export menu


> import options seemed quite technical, so it could be hidden on the rightmost for non-expert users

i think in the minimal scenario it's usually enough to use only import options, without manually modifying any others, since in import options you could choose some of pre-defined theme templates

**Comment by nana-4** [comment] 2019-01-10 19:45
> from technical side of view, i mean the content of plugin's theme_model_extra theme options list

Ah, do you mean that the ["Desktop Environments" section](https://github.com/themix-project/oomox/blob/9e00ad115f47a28f5e3229c48896424734c78291/plugins/theme_oomox/oomox_plugin.py#L169-L190) should be in the "Other" stack? If so, I have no idea why you think that is better... IMO, `theme_model_extra` options should be merged into `theme_model_options` and should be handled in the "Theme" stack.

> the number of export plugins is not limited, so it could became a bit misleading what one plugins are exporting their result implicitly on Export button and other would require explicitly selecting them in the export menu

So, how about changing the "Export" button label depending on the stack-switcher button? For example,  while on the "Terminal" stack, the blue button label will be "Export Terminal".

**Comment by actionless** [comment] 2019-01-10 20:07
in the theme plugin which you linked it's already merged, the line which you're pointing is commented out

theme_model_extra was aimed for exports which are not covered by normal Export Theme flow, like at the moment Spotify (but i hope more export plugins will come with the time)


> So, how about changing the "Export" button label depending on the stack-switcher button? For example, while on the "Terminal" stack, the blue button label will be "Export Terminal".

that could be better from the point of clarity though i still think this (https://github.com/themix-project/oomox/issues/185#issuecomment-449930291) approach would be more straight-forward and discoverable

**Comment by nana-4** [comment] 2019-01-11 08:33
Ah, I only searched for `theme_model_extra` in this repo and didn't know it exists in the `oomoxify` repo. Sorry.

However, I still think it would be better to have to have the "Spotify" stack (etc.) instead of "Other" stack. I think that should be more clear.

> that could be better from the point of clarity though i still think this (#185 (comment)) approach would be more straight-forward and discoverable

Honesty, I'm not a fan of it. It still quite wastes the headerbar width. Also I'd feel strange if there are other "Export (Theme|Icons|Spotify)" buttons while on the "Terminal" stack.

**Comment by nana-4** [comment] 2019-01-11 08:41
BTW, I found another app with lists based on HIG. Please try [Podcasts](https://gitlab.gnome.org/World/podcasts).

**Comment by actionless** [comment] 2019-01-11 12:09
> However, I still think it would be better to have to have the "Spotify" stack (etc.) instead of "Other" stack. I think that should be more clear.

i explained what  Spotify is just plugin, not part of the app, `especially keeping in mind what in Flatpak installation Spotify plugin is not available at all`

>  wastes the headerbar width

could you just for a reference make a screenshot? because in AwesomeWM (with normal window decorations so without titlebar buttons in CSD) it looks quite clean

**Comment by actionless** [comment] 2019-01-11 12:12
> Please try Podcasts.

thanks, i'll check it tonight

**Comment by nana-4** [comment] 2019-01-11 13:36
> i explained what Spotify is just plugin, not part of the app, especially keeping in mind what in Flatpak installation Spotify plugin is not available at all

How about any of these?

- If Spotify plugin is not available, hide "Spotify" button from stack-switcher.
  - Or make "Spotify" button disable.
- Or make Spotify plugin part of the app (if possible). I always wondered why Spotify is handled in the different repository despite Terminal is part of the app.

> could you just for a reference make a screenshot?

I took some screenshots with several themes on GNOME Shell with minimum window size.

Adwaita:

![image](https://user-images.githubusercontent.com/9556384/51034359-dfee2400-15e9-11e9-9c74-3cab7f8de203.png)

Materia:

![image](https://user-images.githubusercontent.com/9556384/51034368-e5e40500-15e9-11e9-8005-5a0602adbc18.png)

Arc (with all window control buttons):

![image](https://user-images.githubusercontent.com/9556384/51034375-ea102280-15e9-11e9-98a3-54026df54426.png)

Numix (with all window control buttons):

![image](https://user-images.githubusercontent.com/9556384/51034380-eda3a980-15e9-11e9-9a41-8c116c9a7878.png)

On GNOME with minimum window size, "Export Theme" button is almost in the center, and the window title is almost omitted.

> because in AwesomeWM (with normal window decorations so without titlebar buttons in CSD) it looks quite clean

Also Numix/Oomox has narrow side padding in `button.text-button`, but most other themes are not ;)

**Comment by actionless** [comment] 2019-01-11 14:14
> Or make "Spotify" button disable.

i want to make less logic in app itself, because it's always better architecture when there is a minimalistic core which provides common API for plugins rather than implementing each case separately

looking on the screenshots i think what, given "Export Terminal" is the longest label and what `.linked` style will reduce inter-button spacing, i think it should address the problem with too much ellipsis-ed title. Also after refactoring left sidebar application have a minimal width, so user can't resize it to became too small to make any of top controls unreachable

**Comment by actionless** [comment] 2019-01-11 14:53
> despite Terminal is part of the app.

particularly Xresources import and export (which triggered when you click Export Terminal button) is also going to be factored out into a plugin

however terminal options section and preview themselves are common parts of the app, since it could be used for generating any other terminal themes, not only normal ones which supporting Xresources. For example, currently via Base16 plugin it's already possible to export terminal themes for Gnome Terminal, Alacritty and others.

**Comment by nana-4** [comment] 2019-01-15 17:33
I'm sorry for the late reply. And thank you for your explanation. I understand.

I updated the mockup based on the discussion. What do you think?


![image](https://user-images.githubusercontent.com/9556384/51195219-fff64e00-192f-11e9-940b-54e322511d3b.png)

**Comment by actionless** [comment] 2019-01-15 18:07
i am still not feeling well about moving Export button somewhere far away (ie making more clicks)

i wasn't expecting what such a small UI change will require so many discussion behind but it is what it is :-)

**Comment by nana-4** [comment] 2019-01-15 19:01
> i am still not feeling well about moving Export button somewhere far away (ie making more clicks)

Hmm, I thought moving Export buttons to each stack/list is logical and easy-to-understand for end users (especially people who are unfamiliar with oomox-gui).

> i wasn't expecting what such a small UI change will require so many discussion behind

LOL, me too. However, since this app's author is you, I don't mind at all even if you adopt your current design idea as it is. Don’t worry about it :)

**Comment by actionless** [comment] 2019-01-15 19:13
> Hmm, I thought moving Export buttons to each stack/list is logical and easy-to-understand for end users (especially people who are unfamiliar with oomox-gui).

yeah, it could be easier to understand from the first look, but my point what after already knowing the meaning of buttons it could be annoying doing extra clicks

the idea is what all the core actions (ie the ones which always available not depending on which of the plugins are currently available) should try to stay in 1-click availability

also in gthumb such pattern of using linked groups seems to look fine:

![2019-01-15--1547579389_1259x174_scrot](https://user-images.githubusercontent.com/1655669/51203698-fce46900-1901-11e9-9e23-919df743a714.png)

![2019-01-15--1547579398_1250x114_scrot](https://user-images.githubusercontent.com/1655669/51203703-0077f000-1902-11e9-8d06-6fca8ccaa37d.png)

**Comment by nana-4** [comment] 2019-01-16 16:50
> yeah, it could be easier to understand from the first look, but my point what after already knowing the meaning of buttons it could be annoying doing extra clicks

I see. I have to admit that my design approaches are mainly for most of end users (including oomox beginners), but (maybe) not for power users.

For the sake of clarity, one of my design goal was to get rid of such comments you mentioned before:

> i saw few comments on reddit what "it's too complicated to make theme using oomox"

Unless Oomox takes a design easy to understand even for beginners, I think such comments will keep appearing. I think it's a trade-off whether to take a design for most end users (including beginners), or take a design for power users.

By the way, from my point of view, the gthumb headerbar isn't very good UI/UX...

**Comment by nana-4** [comment] 2019-01-16 16:51
> my point what after already knowing the meaning of buttons it could be annoying doing extra clicks

Hmmm, I'm wondering how many people want to click the Export buttons quickly without carefully checking the style. I guess most people want to check the styles/colors/options before clicking the Export buttons.

**Comment by actionless** [comment] 2019-01-16 17:11
> I think it's a trade-off whether to take a design for most end users (including beginners), or take a design for power users.

yeah, it's somehow obvious. but still i wanna think what there is a way to find such a "golden mean" where application will became more friendly for the new users without affecting users who already learned how to use the app

**Comment by actionless** [comment] 2019-01-17 17:03
```
[ + ] dropdown ; [ Save ] button                         Title                             [ Export theme | Icons | v ]     [ Burger ]
```

also i was thinking mb to group rename/delete/clone as linked button:

```
[ Save | v ]
```

motivation behind this -- what currently on the left of the panel there are actions which apply to presets and and on the right -- which apply to generated theme; to be symmetrical with preset list being on the left and generated theme preview on the right

**Comment by nana-4** [comment] 2019-01-17 19:11
I rather moved "Save" etc. to the right, with an opposite idea:

- Left panel is the list of presets, so "Import (something to the list)" button is on left.
- Right panel is the edit screen of the current preset, so "Save", "Save as" etc. on right.

**Comment by actionless** [comment] 2019-01-17 20:44
after looking on the mockups i see what your proposal totally inline with them

however looking on the mockups i see one important difference:
in the mockups they're using Burger menu for app-level actions, and 3-vertical-dots menu for item-level actions. while in your mockups both are residing under Burger menu (which seems semantically incorrect)

**Comment by actionless** [comment] 2019-11-29 11:45
it's almost a year passed, but unfortunately GTK3 still doesn't have (doesn't have documented?) the widgets or style classes to make such a design for main lists to happen

in gnome-tweak-tool and gnome-control-center it seems they just have some custom styling or so (at least that's what i see from gtk inspector)

**Comment by nana-4** [comment] 2019-12-07 09:14
Yep, it seems such a design is realized by using `.ui` files in all GTK3 apps (at least as far as I can see).

For example:
https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/panels/universal-access/cc-ua-panel.ui#L108
https://gitlab.gnome.org/World/gcolor3/blob/master/data/window.ui#L177

(So sorry for my long silence.)

**Comment by actionless** [comment] 2019-12-07 16:55
ok, thanks a lot @nana-4 
i think i'm getting somewhere with that:

![2019-12-07--1575737654_2026x1857_scrot](https://user-images.githubusercontent.com/1655669/70377938-c6994900-191a-11ea-8ba2-806c092da4c2.png)

**Comment by actionless** [comment] 2019-12-07 17:48
still looks a bit crappy but moving somewhere :)

![2019-12-07--1575740856_1705x1570_scrot](https://user-images.githubusercontent.com/1655669/70378559-17f90680-1922-11ea-8d51-fb7ffeee8696.png)

**Comment by actionless** [comment] 2019-12-07 18:37
hm, but it seems what the further work would first require me to refactor the theme model as it stored in plugins from being just a list into being some structure what will be split into sections (now section names are just parts of the list together with actual theme values/options)

**Comment by actionless** [comment] 2020-08-03 15:30
@nana-4 

sorry for the delay on this issue :) 

finally got to finish it, please check on this branch: https://github.com/themix-project/oomox/tree/redesign-main-lists

![2020-08-03--1596468420_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/89199524-f9313980-d5ae-11ea-82db-08d8c1cda3d3.png)

**Comment by nana-4** [comment] 2020-09-16 16:17
@actionless My apologies for the late reply...!

I tried the branch, it looks very nice! Great job! :+1:

I think this is already close to perfection, but I think it would be even better if you could do these things:

- Add separators between the list rows, like my mockup.
- Remove less meaningful hover/active effects from the list rows (perhaps by setting activatable=FALSE).
- Add a vertical GtkSeparator between GtkPaned and the theme preview, like my mockup.

And personally I'd still prefer to separate the `Theme Style` and `Theme Colors` into separate sections (otherwise, end users may misunderstand that the `Theme Options` is independent of the `Theme Style`.), but I'll leave the decision to you :)

**Comment by actionless** [comment] 2020-09-16 18:04
> Add separators between the list rows, like my mockup.

such separators should be defined in GTK theme, not as a border widget (you can see gtk-inspector on the left as an example)

> Remove less meaningful hover/active effects 

> Add a vertical GtkSeparator between GtkPaned and the theme preview, like my mockup.

> to separate the Theme Style and Theme Colors into separate sections

good points, thanks

**Comment by nana-4** [comment] 2020-09-17 13:01
> such separators should be defined in GTK theme, not as a border widget (you can see gtk-inspector on the left as an example)

Looking at `gtk3-widget-factory`'s code, apparently it actually calls GtkSeparator for the list box on "Page 2" by using [`gtk_list_box_set_header_func ()`](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/demos/widget-factory/widget-factory.c#L1833) and its own [`update_header ()`](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/demos/widget-factory/widget-factory.c#L511-525).  The`gnome-control-center` application also uses a [similar function](https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/common/list-box-helper.c#L66-86).

But I don't know if such a method can be applied to this project. So, I'm OK without the separators :ok_hand:

**Comment by actionless** [comment] 2020-09-17 18:07
i see it now in gtk3-widget-factory, that's quite weird what they have the same element styled differently across default apps

does they have any HIG part describing it?

**Comment by nana-4** [comment] 2020-09-18 05:42
https://developer.gnome.org/hig/stable/lists.html.en

> In standard lists, each row is divided by separators,

This means you can optionally remove the list separators, I guess?

Typically, GNOME apps have separators in list boxes that contain action controls in each row. Lists that don't contain action controls, such as sidebars, usually don't have a separator for each row.

The lists in the GtkInspector seems to deviate from the typical design. I think GNOME designers weren't very involved in the design of it...

**Comment by actionless** [comment] 2020-09-18 17:35
after looking on the HIG i'm even more grounded in the theory which i had yesterday about it :) 

the theory is what 
1) by design they wanted all list items to have the separators
2) they added those borders in the gtk theme
3) it broken visually some of the popular third-party gtk apps
4) they moved borders logic from the theme to the app

**Comment by actionless** [comment] 2020-09-20 00:02
@nana-4  i've tried to implement all of your recommendations, please check on the master branch

**Comment by nana-4** [comment] 2020-09-20 02:02
> 2. they added those borders in the gtk theme

According to my memory and a little search, the default GTK theme had never defined borders for each list row. But now, GTK4 has a boolean [GtkListBox:show-separators](https://developer.gnome.org/gtk4/stable/GtkListBox.html#GtkListBox--show-separators) and the separators are drawn by theme :)

**Comment by nana-4** [comment] 2020-09-20 02:02
> @nana-4 i've tried to implement all of your recommendations, please check on the master branch

Looks awesome! Thanks!

One remaining issue: Can we avoid using a list for `Theme Style`, and make it like my mockup? GNOME apps don't use a list if it has only one item. And the [GNOME HIG](https://developer.gnome.org/hig/stable/lists.html.en) says:

> Do not use lists with fewer than about five items, unless the number of items may increase over time.

**Comment by actionless** [comment] 2020-09-20 02:07
regarding separators, yeah, i know it wasn't released, but just judging from mockups and related HIG -- it seems it was designed to be, but they either tried that locally or realized without trying what it might break things visually. but anyway that was just a lyric sidenote after reading that HIG :)

_________

regarding list items

it falls under

> unless the number of items may increase over time.

because programmatically it's just one of theme sections, the same as others below (or above, if in plugin mode)

**Comment by nana-4** [comment] 2020-09-20 02:19
> because programmatically it's just one of theme sections, the same as others below (or above, if in plugin mode)

OK, that's fine then :+1:

**Comment by actionless** [comment] 2020-09-20 02:21
thanks for your input and feedback!

**Closed** 2020-09-20 02:20 UTC
Labels: discussion, in progress

**Comment by nana-4** [comment] 2020-09-20 02:23
Thanks for your great work and feedback too :)
