### ISSUE TITLE
Outline despite of outline=0

### ISSUE THREAD

**Issue by jdamboeck** [themix-project/oomox#123] opened 2018-02-14 19:55 UTC
Outline despite of outline=0.. also what is this glow around the windows?
![screenshot from 2018-02-14 20-52-11](https://user-images.githubusercontent.com/20957463/36224809-f609fc3a-11c8-11e8-8d7a-692e3361ee68.png)

oomox 1.5 arch

**Comment by actionless** [comment] 2018-02-14 22:25
1) outline is a border which is displayed over an item selected with keyboard (with <Tab>key)

2) glow is inverted shadow (for dark themes)

**Comment by jdamboeck** [comment] 2018-02-15 13:06
Yeah... I know what an outline is. But I disabled the outline then why is it still there.
As for the shadow, there should be a switch to just keep it as a shadow instead of a glow with dark themes.

**Comment by actionless** [comment] 2018-02-15 14:10
1. could you highlight the mistaken outline on your screenshot?

2. i'll be happy to merge such change

**Comment by jdamboeck** [comment] 2018-02-15 15:37
1. Okay.. I made a mistake.. there is an option focused outline width. i thought it relates to the window border but its the selected item in other elements.

but there is another error.

see the attached screens:
![screenshot1](https://user-images.githubusercontent.com/20957463/36264885-3e981144-126e-11e8-9bac-2cb23b6486b0.png)
![screenshot2](https://user-images.githubusercontent.com/20957463/36264886-3eb6dc8c-126e-11e8-88cd-c785b069c582.png)

2. That would be really great

**Comment by actionless** [comment] 2018-02-15 16:01
does the problem happens only with Telegram (and other google-chrome/electron-based apps) ?

if so -- that could be a duplicate of this issue:
https://github.com/actionless/oomox/issues/121 (Slack in that ticket AFAIK is using electron)

**Comment by jdamboeck** [comment] 2018-02-15 16:06
it happen with all windows that use a small window decoration(tool style window i think). gimp for example or the oomox popup when you export the theme.

**Comment by actionless** [comment] 2018-02-15 17:27
i still can't reproduce it but let's try to debug it:

1) which WM do you use?

2) create a file `~/.config/gtk-3.0/gtk.css` and put there:
```css
window decoration {
	margin: 0;
	border: none;
}
```
restar the app and see if it helped

**Comment by jdamboeck** [comment] 2018-02-15 17:53
1. i cant change my WM decorations.
2. i am using gnome 3.26.2
3. stays the same

**Comment by jdamboeck** [comment] 2018-02-15 18:03
3. Okay.. After login back the faulty outline is gnone... but the outline is always the focused window border color

**Comment by jdamboeck** [comment] 2018-02-15 18:30
and... when i change the border color... the faulty border on non focused tool style windows stays the same color as before.

**Comment by actionless** [comment] 2018-02-15 18:44
> i cant change my WM decorations.

if your WM not offering such option you can create a "fake" theme:
1) generate oomox theme normally
2) remove `metacity-1` directory from the generated theme
3) copy that directory from some other non-oomox theme

**Comment by actionless** [comment] 2018-02-15 18:46
> and... when i change the border color... the faulty border on all tool style windows stays the same color as before. so i think there maybe an bug when applying the color to those windows.

are they applying after re-logging-in to the gnome?

**Comment by jdamboeck** [comment] 2018-02-15 18:50
> are they applying after re-logging-in to the gnome? 
ah.. yes they do

**Comment by jdamboeck** [comment] 2018-02-15 18:52
As for the metacity theme... i think gnome does not use that anymore?
most of my themes have no metacity folder. also if i delete that folder everything is still as intended

**Comment by actionless** [comment] 2018-02-15 18:54
so, just to confirm it's not using metacity:

when you're doing this sequence:
1) change to some other theme
2) remove `metacity-1` from oomox theme
3) choose back oomox theme 
4) relogin to gnome

you're still able to reproduce the issue or you're seeing some default Adwaita titlebars?

**Comment by jdamboeck** [comment] 2018-02-15 18:59
yes... but i can't resize the windows with csd anymore. the buggy windows stay the same

![screenshot from 2018-02-15 19-58-52](https://user-images.githubusercontent.com/20957463/36275277-b1e0ad8e-128a-11e8-99a4-8c5bbc412972.png)

**Comment by jdamboeck** [comment] 2018-02-15 19:07
okay.. no matter what i change it stays visually the same

**Comment by actionless** [comment] 2018-02-15 19:48
then i guess now gnome is reading  them from gtk theme

does editing `./oomox/plugins/theme_oomox/gtk-theme/src/gtk-3.20/scss/widgets/_window.scss` have any effect for the issue? because there i don't see any separate handling of CSD and non-CSD windows, while on your screenshots i see what CSD and non-CSD windows have slightly different decorations (so i've suggested what on non-CSD it's metacity)

**Comment by jdamboeck** [comment] 2018-02-15 19:55
for that i would have to compile it myself i think?

**Comment by actionless** [comment] 2018-02-15 19:58
you can just edit /opt/oomox/plugins/theme_oomox/gtk-theme/src/gtk-3.20/scss/widgets/_window.scss with sudo

**Comment by jdamboeck** [comment] 2018-02-15 19:58
nevermind... checked the source out. nothing to compile i think.

**Comment by actionless** [comment] 2018-02-15 20:08
i particularly recommend playing with the line 40 (`.ssd`) or you can do it in your ~/.config/gtk-3.0/gtk.css

**Comment by jdamboeck** [comment] 2018-02-15 20:36
changing .ssd does indeed change the windows in question... now im on the hunt for any documentation on that.. but good luck searching for searches with ssd as a term :D

**Comment by jdamboeck** [comment] 2018-02-15 20:57
that did the trick
``` 
.ssd & {
    box-shadow: 0 0 0 1px $wm_border_focused;
    &:backdrop {
        box-shadow: 0 0 0 1px $wm_border_unfocused;
     }
}
```
![screenshot from 18 02](https://user-images.githubusercontent.com/20957463/36280623-26d450f4-129b-11e8-8fb9-9ab0aadf96fd.png)

**Comment by jdamboeck** [comment] 2018-02-15 22:27
but the issue #121 is still there.. it applies the right color but there is a double border. the one from the ssd and inside that another one which does not include the titlebar. 
with csd there are also 2 borders... but they include the window title too.

![screenshot from 18 02](https://user-images.githubusercontent.com/20957463/36284380-bd51f124-12a7-11e8-9fcf-4d5c931be3b1.png)

**Comment by actionless** [comment] 2018-02-16 00:19
if you set `window decoration { border-width: 0; }` it looks fine but mouse not resizing the edges?

**Comment by jdamboeck** [comment] 2018-02-16 00:29
yes

**Comment by actionless** [comment] 2018-02-16 00:31
and what about:

```scss
window decoration {
border-width: $spacing + 2px;
}

window {
border-radius: $roundness / 2;
}
```

?

**Comment by jdamboeck** [comment] 2018-02-16 00:34
The same as as without gtk.css

**Comment by actionless** [comment] 2018-02-16 00:35
you need to compile in your head that scss snippet into css using the real values from your preset :-)

**Comment by actionless** [comment] 2018-02-16 00:38
should look like that:

![2018-02-16--1518741434_1912x719_scrot](https://user-images.githubusercontent.com/1655669/36288251-a1d77194-12b1-11e8-863c-6a14ed39e68a.png)

**Comment by jdamboeck** [comment] 2018-02-16 00:39
ah lol.. .. where do i put that?

**Comment by actionless** [comment] 2018-02-16 00:40
i mean replace $roundness and and $spacing to real values and compute the math, so it will be css in the end, and put to gtk.css to try

**Comment by jdamboeck** [comment] 2018-02-16 00:47
get's even worse
![screenshot from 18 02](https://user-images.githubusercontent.com/20957463/36288528-51744a4c-12bb-11e8-8c4e-970cc60c1194.png)

**Comment by actionless** [comment] 2018-02-16 00:48
weird, in my case the second border is the same color as titlebar

**Comment by actionless** [comment] 2018-02-16 00:51
btw, the green border on your screenshot is not draggable anywhere, not even around titlebar?

**Comment by jdamboeck** [comment] 2018-02-16 00:55
but your screen is not ssd... and the draggable part is only with csd windows

**Comment by jdamboeck** [comment] 2018-02-16 01:01
i have a spacing of 3 and a roundness of 0
so my gtk.css is now:

``` css
window` decoration {
	margin: 0;
	border-width: 5px;
}

window {
	border-radius: 0;
}
```

**Comment by actionless** [comment] 2018-02-16 01:07
hm, mb i'll have a look how that part implemented in other themes

**Comment by jdamboeck** [comment] 2018-02-16 01:33
if i pick a default color sheme and export it i too get the same color as the titlebar... when i edit "focused window border" "unfocused window border" and "background" the strange double border is back again.

**Comment by actionless** [comment] 2018-02-16 02:30
that black color is coming from `WM_BORDER_UNFOCUS=000000`

**Comment by jdamboeck** [comment] 2018-02-16 10:56
Yeah  it why.

**Comment by jdamboeck** [comment] 2018-02-16 11:43
https://www.reddit.com/r/archlinux/comments/6duktu/adding_colored_window_borders_in_gnome/di9htfj/

if i put that part in my gtk.css it works as intended. maybe it helps finding a solution.

**Comment by actionless** [comment] 2018-02-16 12:28
could you please check if the same theme still works fine in openbox?
last time when i was playing with i remember what it was working either in one place or in another.
so if it will be like that again -- mb we can have to _window.scss files and choose one for gnome or for the rest as oomox export option

**Comment by jdamboeck** [comment] 2018-02-16 12:40
in openbox all is as intended

**Comment by actionless** [comment] 2018-02-16 12:42
splendid! could you prepare a pull request please?

**Comment by jdamboeck** [comment] 2018-02-16 12:44
what for? i did not do anything... maybe we did missunderstand each other?

**Comment by actionless** [comment] 2018-02-16 12:46
> if i put that part in my gtk.css it works as intended
> in openbox all is as intended

**Comment by jdamboeck** [comment] 2018-02-16 12:52
yeah.. but i don't really know where to apply the gtk.css changes to the oomox -gtk-theme code.

**Comment by actionless** [comment] 2018-02-16 13:02
you can see similar class names in _window.scss which i mentioned few times above

if you'll not manage to do so, i'll have some time mb on sunday to give it a try

**Comment by jdamboeck** [comment] 2018-02-16 13:04
I will try to sherlock some more... Maybe I'll get my feet in it.

**Comment by actionless** [comment] 2018-02-16 13:15
after that you could SCSS to your CV ;P

**Comment by actionless** [comment] 2018-05-23 15:30
moved to https://github.com/themix-project/oomox-gtk-theme/issues/52

**Closed by actionless** 2018-05-23 15:30 UTC
