### ISSUE TITLE
Request support for importing external themes and making changes to them

### ISSUE THREAD

**Issue by t0xic0der** [themix-project/oomox#345] opened 2020-12-02 06:53 UTC
As of now, the GUI only supports importing color schemes but not GTK themes made by someone else. It would be an awesome feature to have this and folks would be able to mix and match the combinations of themes as well as colors.

**Comment by actionless** [comment] 2020-12-02 20:07
duplicate of https://github.com/themix-project/oomox/issues/33

**Closed by actionless** 2020-12-02 20:07 UTC
